import React, { useEffect, useState } from "react";
import Slider from "react-slick";
import "./headershop.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Section from "../velo/Section";
import sanity from "../Sanity/sanity";
import { PrevArrow, NextArrow } from "../header/CustomArrow";
import { Link } from "react-router-dom";
import Atropos from "atropos/react";
import "atropos/css";

export default function Headershop() {
  const [products, setProducts] = useState([]);

  const handleClicks = () => {
    // Scroll to the top of the SingleItemDetail component
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  useEffect(() => {
    const fetchProducts = async () => {
      // **create slug and these slug autogenerated , these slug used to navigate to single component
      try {
        const productQuery = `*[_type == "product"]{
          productTitle,
          slug,  

          productimg1 { asset->{ _id, url }},
          productimg2 { asset->{ _id, url }},
          productimg3 { asset->{ _id, url }},
          productimg4 { asset->{ _id, url }},
          productprice
        }`;

        const res = await sanity.fetch(productQuery);

        setProducts(res);
        console.log(res);
      } catch (error) {
        console.log(error);
      }
    };
    fetchProducts();
  }, []);

  const mainSliderSettings = {
    dots: false,
    speed: 1900,
    slidesToShow: 3,
    slidesToScroll: 1,
    autoplaySpeed: 3200,
    className: "center",
    centerMode: true,
    infinite: true,
    centerPadding: "60px",
    cssEase: "linear",
    autoplay: true,
    rtl: true,
    prevArrow: <PrevArrow />,
    nextArrow: <NextArrow />,
    className: "custom-slider",
  };

  const individualCardSliderSettings = {
    dots: true,
    speed: 1000,
    fade: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplaySpeed: 1,
    arrows: false,
    autoplay: false,
  };

  return (
    <div className="main_headershop">
      <Section />
      <div className="mainer">
        <Slider {...mainSliderSettings}>
          {products &&
            products.map((header) => (
              <div key={header.slug?.current} className="">
                <div className="">
                  {/* **go to single to slug string with link */}

                  <Slider {...individualCardSliderSettings}>
                    {header.productimg1 && (
                      <div
                        className="sub_shop"
                        key={`main-${header.slug?.current}-img1`}
                      >
                          <img
                            src={header.productimg1.asset.url}
                            alt={header.productTitle}
                            loading="lazy"
                            title={header.productTitle}
                          />
                      </div>
                    )}
                    {header.productimg2 && (
                      <div
                        className="sub_shop"
                        key={`main-${header.slug?.current}-img2`}
                      >
                        <img
                          src={header.productimg2.asset.url}
                          alt={header && header.productTitle}
                          loading="lazy"
                        />
                      </div>
                    )}
                    {header.productimg3 && (
                      <div
                        className="sub_shop"
                        key={`main-${header.slug?.current}-img3`}
                      >
                        <img
                          src={header.productimg3.asset.url}
                          alt={header && header.productTitle}
                          loading="lazy"
                        />
                      </div>
                    )}
                    {header.productimg4 && (
                      <div
                        className="sub_shop"
                        key={`main-${header.slug?.current}-img4`}
                      >
                        <img
                          src={header.productimg4.asset.url}
                          alt={header && header.productTitle}
                          loading="lazy"
                        />
                      </div>
                    )}
                  </Slider>

                  <Link
                    className="linka"
                    onClick={handleClicks}
                    to={`/product/${header.slug?.current}`}
                    key={header.slug?.current}
                  >
                    <h4 className="price">{header.productprice}</h4>
                    <h3 className="shop_title">
                      <div className="arrower" />

                      {header && header.productTitle}
                    </h3>
                  </Link>
                </div>
              </div>
            ))}
        </Slider>
      </div>
    </div>
  );
}
